---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-7.1

suites:
  - name: java6
    run_list:
      - recipe[java]
      - recipe[keytool::default]
      - recipe[keytool::test]
    attributes:
      java:
        jdk_version: 6
    includes:
      - centos-6.5
  - name: java7
    run_list:
      - recipe[java]
      - recipe[keytool::default]
      - recipe[keytool::test]
    attributes:
      java:
        jdk_version: 7
    includes:
      - centos-6.5
